---
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    groups:
      - matrix
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"

        matrix_homeserver_url: "{{ lookup('env', 'MATRIX_HOMESERVER_URL') }}"
        matrix_room_id: "{{ lookup('env', 'MATRIX_ROOM_ID') }}"
        matrix_access_token: "{{ lookup('env', 'MATRIX_ACCESS_TOKEN') }}"
        matrix_admin_user: "{{ lookup('env', 'MATRIX_ADMIN_USER') }}"
        matrix_admin_token: "{{ lookup('env', 'MATRIX_ADMIN_TOKEN') }}"

scenario:
  test_sequence:
    - destroy
    # - create
    # - prepare
    - converge
    # - idempotence
    - verify
    - destroy

verifier:
  name: ansible
