---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: synapse-test
    groups:
      - matrix
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml
  inventory:
    group_vars:
      all:
        matrix_homeserver_url: "http://localhost:8008"
        matrix_admin_user: "@admin:matrix.test"
        matrix_admin_password: "molecule_admin_password"
        matrix_bot_user: "@bot:matrix.test"
        matrix_bot_password: "molecule_bot_password"
        matrix_room_alias: "test-room"
        matrix_room_id: "#test-room:matrix.test"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: ansible
