---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Generate Synapse config (using container as generator)
      ansible.builtin.command:
        cmd: >
          docker run --rm 
          -v {{ molecule_ephemeral_directory }}/synapse_data:/data 
          -e SYNAPSE_SERVER_NAME=matrix.test 
          -e SYNAPSE_REPORT_STATS=no 
          matrixdotorg/synapse:latest generate
      delegate_to: localhost
      changed_when: true

    - name: Inject custom homeserver.yaml
      ansible.builtin.copy:
        src: files/homeserver.yaml
        dest: "{{ molecule_ephemeral_directory }}/synapse_data/homeserver.yaml"
        mode: '0644'
      delegate_to: localhost

    - name: Ensure correct ownership of data dir
      ansible.builtin.command:
        cmd: "chmod -R 777 {{ molecule_ephemeral_directory }}/synapse_data"
      delegate_to: localhost
      changed_when: true

    - name: Start synapse process in container
      ansible.builtin.command:
        cmd: >
          docker run -d 
          --name {{ inventory_hostname }} 
          --network matrix-net
          -p 8008:8008 
          -v {{ molecule_ephemeral_directory }}/synapse_data:/data 
          matrixdotorg/synapse:latest
      delegate_to: localhost
      changed_when: true

    - name: Wait for Synapse to be healthy
      ansible.builtin.uri:
        url: "{{ matrix_homeserver_url }}/health"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5
      delegate_to: localhost

    - name: Register admin user
      ansible.builtin.command:
        cmd: >
          docker exec {{ inventory_hostname }} 
          register_new_matrix_user 
          -c /data/homeserver.yaml 
          -u admin 
          -p {{ matrix_admin_password }} 
          --admin 
          --no-review 
          http://localhost:8008
      delegate_to: localhost
      changed_when: true
