---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    # Look up Matrix connection details from environment variables
    matrix_homeserver_url: "{{ lookup('env', 'MATRIX_HOMESERVER_URL') | default('https://matrix-web.jackaltx.com') }}"
    matrix_room_id: "{{ lookup('env', 'MATRIX_ROOM_ID') | default('#solti-verify:jackaltx.com') }}"
    matrix_access_token: "{{ lookup('env', 'MATRIX_ACCESS_TOKEN') }}"

  tasks:
    - name: Fail if MATRIX_ACCESS_TOKEN is not set
      ansible.builtin.fail:
        msg: "The MATRIX_ACCESS_TOKEN environment variable is not set."
      when: matrix_access_token | length == 0

    - name: Create report directory
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: '0755'

    - name: Build content for a test event
      ansible.builtin.set_fact:
        test_event_content:
          msgtype: "m.text"
          body: "Molecule test event for jackaltx.solti_matrix_mgr"
          solti:
            schema: "test.v1"
            source: "molecule/default"
            data:
              message: "This is a test event from a Molecule scenario."
              timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Post the test event to Matrix
      jackaltx.solti_matrix_mgr.matrix_event:
        homeserver_url: "{{ matrix_homeserver_url }}"
        access_token: "{{ matrix_access_token }}"
        room_id: "{{ matrix_room_id }}"
        content: "{{ test_event_content }}"
      register: matrix_event_result

    - name: Store the result for verification
      ansible.builtin.copy:
        content: "{{ matrix_event_result | to_nice_json }}"
        dest: "{{ report_root }}/matrix_event_result.json"
