---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    groups:
      - matrix
provisioner:
  name: ansible
  options:
    ansible_args:
      - --skip-tags
      - idempotence-skip
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_connection: local
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"
verifier:
  name: ansible
