---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    groups:
      - matrix
provisioner:
  name: ansible
  env:
    ANSIBLE_SKIP_TAGS: "idempotence-skip"
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_connection: local
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"
verifier:
  name: ansible
