---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    groups:
      - matrix
provisioner:
  name: ansible
  env:
    ANSIBLE_SKIP_TAGS: "idempotence-skip"
    # Propagate Matrix environment variables
    MATRIX_HOMESERVER_URL: "{{ lookup('env', 'MATRIX_HOMESERVER_URL') }}"
    MATRIX_ROOM_ID: "{{ lookup('env', 'MATRIX_ROOM_ID') }}"
    MATRIX_ACCESS_TOKEN: "{{ lookup('env', 'MATRIX_ACCESS_TOKEN') }}"
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_connection: local
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"
verifier:
  name: ansible
