---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Verification placeholder
      ansible.builtin.debug:
        msg: "Verification step. The converge playbook already asserted the successful posting of the event."
